const Map<String, String> ja = {
  'title': 'gemai',
  //settings
  'settings_title': '設定',
  'settings_language': '言語を変更',
  'settings_dark_mode': 'ダークモード',
  'settings_share': 'アプリを共有',
  'settings_rate': 'アプリを評価',
  'settings_contact': 'お問い合わせ',
  'settings_about': 'アプリについて',
  'settings_privacy': 'プライバシーポリシー',
  'settings_terms': '利用規約',
  'settings_faq': 'よくある質問',
  'settings_version': 'バージョン',
  'settings_restore_purchases': '購入を復元',
  'settings_share_title': 'アプリを共有',
  'settings_rate_title': 'アプリを評価',
  'settings_restore_purchases_success': '購入が正常に復元されました！',
  'settings_restore_purchases_error': '購入の復元に失敗しました：',
  'settings_privacy_error': 'プライバシーポリシーページを開けませんでした',
  'settings_faq_error': 'よくある質問ページを開けませんでした',
  'settings_terms_error': '利用規約ページを開けませんでした',
  'settings_about_error': 'アプリについてページを開けませんでした',
  'settings_cancel_subscription_error': 'サブスクリプションキャンセルページを開けませんでした',

  //account
  'account_title': 'アカウント',
  'account_anonymous': '匿名ユーザー',
  'account_user_id': 'ユーザーID',
  'account_device_id': 'デバイスID',
  'account_type': 'アカウントタイプ',
  'account_type_basic': 'ベーシック',
  'account_type_premium': 'プレミアム',
  'account_remaining_days': '残り日数',
  'account_remaining_days_info': '日',
  'account_restore_purchases': '購入を復元',
  'account_cancel_subscription': 'サブスクリプションをキャンセル',
  'account_snackbar_copy': 'デバイスIDがコピーされました',

  //premium
  'per_year': '年間',
  'per_month': '月間',
  'per_week': '週間',
  'per_lifetime': '永久',
  'plan_title_yearly': '年間プラン',
  'plan_title_monthly': '月間プラン',
  'plan_title_weekly': '週間プラン',
  'trial_title_days': '{days}日間無料',
  'trial_title_week': '1週間無料',
  'trial_title_month': '1ヶ月無料',
  'plan_title_lifetime': '永久',
  'best_value': 'ベストバリュー',
  'continue': '続行',
  'try_for_free': '無料で試す',
  'free': '無料',
  'save_percent': '%{percent}お得',
  'restore_purchases_success': 'プレミアムサブスクリプションが正常に復元されました！',
  'restore_purchases_info': '復元するアクティブなプレミアムサブスクリプションが見つかりません',
  'restore_purchases_error_premium_expiry_date': 'プレミアムの有効期限を取得できませんでした',
  'restore_purchases_error_user_id': 'ユーザー情報が見つかりません',
  'restore_purchases_error_backend': 'バックエンドの復元に失敗しました',
  'restore_purchases_error_unknown': '復元中に予期しないエラーが発生しました',

  'premium_title': 'プレミアム機能',
  'premium_desc_1': '無制限の肌分析を実行',
  'premium_desc_2': '最新のAIモデルを使用',
  'premium_desc_3': '過去の分析を表示',
  'premium_restore': '復元',
  'premium_terms': '利用規約',
  'premium_privacy': 'プライバシーポリシー',
  'premium_trial_not_available': '無料トライアルは利用できません。',
  'premium_continue_without': 'プレミアムなしで続行',
  'premium_no_packages': '購入オプションが見つかりません。',
  'premium_no_selected_package': '購入するパッケージが見つかりません。',
  'premium_purchase_cancelled': '購入がキャンセルされました。',
  'premium_purchase_failed': '購入に失敗しました。もう一度お試しください。',
  'premium_activated': 'プレミアムサブスクリプションが有効化されました！',
  'premium_restore_error': '復元中にエラーが発生しました',

  // 共有
  'share_result_title': '結果を共有',
  'share_result_error': '共有中にエラーが発生しました：',
  'share_result_share_text': 'gemai - 分析結果\ngemaiで肌を分析しましょう！',

  // プレミアム機能

  //onboarding
  'onboarding_title_1': 'gemaiへようこそ！',
  'onboarding_desc_1': '写真を撮るか、画像を選択して肌分析を行います。肌の問題を即座に発見しましょう。',
  'onboarding_title_2': '強力な人工知能',
  'onboarding_desc_2': '最先端の人工知能を使用して、最高の精度で肌分析を行います。',
  'onboarding_title_3': '結果を発見',
  'onboarding_desc_3': '肌分析の結果を表示し、肌の問題を理解しましょう。',
  'onboarding_skip': 'スキップ',
  'onboarding_next': '次へ',
  'onboarding_start': '開始',

  //home
  'home_welcome_title': 'ようこそ',
  'home_welcome_desc': '肌の分析を開始し、過去の結果を確認しましょう。',
  'home_analyze_button_title': 'タップして肌分析を開始',
  'home_tip_title': 'より良い結果を得るために、日光の下または明るい場所で写真を撮ってください。',
  'home_recent_history_title': '最近の活動',
  'home_recent_history_view_more': 'もっと見る',
  'home_recent_history_no_history': 'まだ分析が行われていません。',
  'home': 'ホーム',
  'history': '履歴',

  //camera
  'camera_scan_title': 'gemai肌スキャナー',
  'camera_scanning': 'gemaiが分析中',
  'camera_scanning_desc': '肌の病気をスキャン中...',
  'camera_scan_desc': '肌の病気を枠内に配置してください',

  //history
  'history_no_history': 'まだ分析が行われていません。',

  // 日付フォーマット用の翻訳キー
  'just_now': '今',
  'minutes_ago': '{count}分前',
  'hours_ago': '{count}時間前',
  'yesterday': '昨日',
  'days_ago': '{count}日前',
  'date_format': 'dd MMM yyyy',

  // お問い合わせメール
  'contact_text': '以下のメールアドレスを使用してお問い合わせください。',
  'contact_mail_subject': 'gemai - お問い合わせ',
  'contact_mail_body_write_here': 'ここにメッセージを書いてください...',
  'contact_mail_user_id': 'ユーザーID',
  'contact_mail_device_type': 'デバイスタイプ',
  'contact_mail_app_name': 'アプリ名',
  'contact_mail_package_name': 'パッケージ名',
  'contact_mail_version': 'バージョン',
  'contact_mail_build_number': 'ビルド番号',
  'could_not_open_mail_app': 'メールアプリを開けませんでした',

  // ページ
  'pages_title': 'ページ',
  'pages_empty': 'まだページがありません。',
  'page_not_found': 'ページが見つかりません。',
  'loading': '読み込み中...',
  'error': 'エラー',
  'retry': '再試行',

  //result
  'result_title': '結果',
  'result_image_title': '画像',
  'result_no_result': '結果が見つかりません。',
  'result_disease_name': '病気の名前',
  'result_contagious': '感染性？',
  'result_severity': '重症度',
  'result_recovery_time': '回復時間',
  'result_symptoms': '症状',
  'result_body_parts': '影響を受ける部位',
  'result_risk_factors': 'リスク要因',
  'result_treatment': '医療治療',
  'result_prevention': '予防方法',
  'result_alternative_treatment': '代替治療',
  'result_description': '説明',
  'result_footer_note': 'これらの結果は情報提供のみを目的としており、推定評価です。医師にご相談ください。',
  'result_image_close': '閉じる',
  'result_severity_low': '非常に軽度',
  'result_severity_medium': '軽度',
  'result_severity_high': '中等度',
  'result_severity_very_high': '重度',
  'result_severity_very_very_high': '非常に重度',
  'result_severity_very_very_very_high': '極度に重度',

  //スキャンダイアログ
  'scan_dialog_title': 'エラー',
  'scan_dialog_title_warning': '警告',
  'scan_dialog_title_error': 'エラー',
  'scan_dialog_title_info': '情報',
  'scan_dialog_title_success': '成功',
  'scan_dialog_400': '無効なデータが送信されました。',
  'scan_dialog_403': 'プレミアムサブスクリプションに移行する必要があります。',
  'scan_dialog_500': 'AIサービスが混雑しています。数分後に再試行してください。',
  'scan_dialog_503': 'サーバーエラーが発生しました。後でもう一度お試しください。',
  'scan_dialog_501': 'メンテナンスモードです。後でもう一度お試しください。',
  'scan_dialog_1001': '画像が肌に関連していません。または肌に問題が見えません。新しい写真を撮ってください。',
  'scan_dialog_5000': 'AIレスポンスを解析できませんでした',
  'scan_dialog_429': 'リクエストが多すぎます。後でもう一度お試しください。',
  'scan_dialog_error': 'エラーが発生しました。後でもう一度お試しください。',
  'scan_dialog_ok': 'OK',
  'scan_dialog_cancel': '閉じる',

  //お問い合わせダイアログ
  'contact_dialog_title': 'お問い合わせ',
  'contact_dialog_message':
      'メールアプリを開いてメッセージを送信しますか？\n\nメールアドレス: contact@gemai.us',
  'contact_email_copied': 'メールアドレスがコピーされました',
  'contact_dialog_cancel': 'キャンセル',
  'contact_dialog_send': 'メール送信',

  //肌分析
  'skin_analysis_title': '肌分析',
  'skin_analysis_age': '年齢',
  'skin_analysis_age_info': '年齢',
  'skin_analysis_age_info_1': '1歳未満',
  'skin_analysis_button_title': '識別',
  'skin_analysis_button_title_loading': '分析中...',
  'skin_analysis_scanning': '分析中...',
  'skin_analysis_scanning_desc': '画像がAIによって分析されています。\nお待ちください。',
  'skin_analysis_body_parts': '影響を受ける部位',
  'skin_analysis_body_parts_selected': '部位が選択されました',
  'skin_analysis_complaints': '詳細 - 症状',
  'skin_analysis_complaints_hint': 'かゆみ、痛み、どのくらい前から、など。ここに症状と重要な詳細を書いてください...',
  'skin_analysis_complaints_char_count': '/500文字',
  'skin_analysis_image': '画像',
  'skin_analysis_body_parts_face': '顔',
  'skin_analysis_body_parts_hair': '頭皮',
  'skin_analysis_body_parts_ear': '耳',
  'skin_analysis_body_parts_neck': '首',
  'skin_analysis_body_parts_hand': '手',
  'skin_analysis_body_parts_leg': '腕',
  'skin_analysis_body_parts_chest': '腹部',
  'skin_analysis_body_parts_breast': '胸',
  'skin_analysis_body_parts_back': '背中',
  'skin_analysis_body_parts_foot': '足',
  'skin_analysis_body_parts_leg_foot': '脚',
  'skin_analysis_body_parts_sex': '陰部',
  'skin_analysis_token_error': 'トークン確認中にエラーが発生しました',
  'skin_analysis_token_error_premium':
      '日次分析の権限が終了しました。プレミアムサブスクリプションに移行してください。',
  'skin_analysis_body_parts_error': '少なくとも1つの影響を受ける部位を選択してください',
  'skin_analysis_complaints_error': '症状を書いてください',
  'skin_analysis_image_error': '画像が見つかりません',
  'skin_analysis_error': '分析中にエラーが発生しました。もう一度お試しください。',

  // 法的警告
  'legal_warning_title': '法的警告',
  'legal_warning_subtitle': '続行する前に、以下の条件を読み、同意してください。',
  'legal_warning_description_1':
      'このアプリは、肌分析のために人工知能技術を使用しています。分析結果は情報提供のみを目的としており、医療診断の代わりにはなりません。',
  'legal_warning_description_2':
      'アプリは分析のために写真を使用します。これらの写真はあなたのデバイスにのみ保存され、第三者と共有されることはありません。',
  'legal_warning_description_3': '重篤な肌の問題がある場合は、必ず皮膚科医にご相談ください。',
  'legal_warning_agreement_title': '利用規約',
  'legal_warning_agreement_1': '分析結果が情報提供のみを目的としており、医療診断の代わりにはならないことに同意します。',
  'legal_warning_agreement_2': 'プライバシーポリシーを読み、同意しました。',
  'legal_warning_agreement_3': '利用規約を読み、同意しました。',
  'legal_warning_checkbox_text': '上記の条件を読み、同意しました',
  'legal_warning_confirm_button': '確認',
  'legal_warning_checkbox_text_error': '続行するには条件に同意してください',
  'legal_warning_error': 'エラーが発生しました、もう一度お試しください',
  'legal_warning_error_no_settings': 'リンクを開けませんでした',

  //インターネットなし
  'no_internet_title': 'インターネット接続なし',
  'no_internet_desc': 'アプリにはインターネット接続が必要です。インターネット接続を確認して、もう一度お試しください。',
  'no_internet_retry': '再試行',
  'no_internet_connection_established': '接続が確立されました',
  'no_internet_connection_not_established': '接続なし',
  'no_internet_refresh': '更新',
  'no_internet_settings': 'ネットワーク設定',
};
