const Map<String, String> ko = {
  'title': 'DERMAI',
  //settings
  'settings_title': '설정',
  'settings_language': '언어 변경',
  'settings_dark_mode': '다크 모드',
  'settings_share': '앱 공유',
  'settings_rate': '앱 평가',
  'settings_contact': '연락처',
  'settings_about': '정보',
  'settings_privacy': '개인정보 처리방침',
  'settings_terms': '이용약관',
  'settings_faq': '자주 묻는 질문',
  'settings_version': '버전',
  'settings_restore_purchases': '구매 복원',
  'settings_share_title': '앱 공유',
  'settings_rate_title': '앱 평가',
  'settings_restore_purchases_success': '구매가 성공적으로 복원되었습니다!',
  'settings_restore_purchases_error': '구매 복원에 실패했습니다:',
  'settings_privacy_error': '개인정보 처리방침 페이지를 열 수 없습니다',
  'settings_faq_error': '자주 묻는 질문 페이지를 열 수 없습니다',
  'settings_terms_error': '이용약관 페이지를 열 수 없습니다',
  'settings_about_error': '정보 페이지를 열 수 없습니다',
  'settings_cancel_subscription_error': '구독 취소 페이지를 열 수 없습니다',

  //account
  'account_title': '계정',
  'account_anonymous': '익명 사용자',
  'account_user_id': '사용자 ID',
  'account_device_id': '기기 ID',
  'account_type': '계정 유형',
  'account_type_basic': '기본',
  'account_type_premium': '프리미엄',
  'account_remaining_days': '남은 일수',
  'account_remaining_days_info': '일',
  'account_restore_purchases': '구매 복원',
  'account_cancel_subscription': '구독 취소',
  'account_snackbar_copy': '기기 ID가 복사되었습니다',

  //premium
  'per_year': '연간',
  'per_month': '월간',
  'per_week': '주간',
  'per_lifetime': '평생',
  'plan_title_yearly': '연간 플랜',
  'plan_title_monthly': '월간 플랜',
  'plan_title_weekly': '주간 플랜',
  'trial_title_days': '{days}일 무료',
  'trial_title_week': '1주 무료',
  'trial_title_month': '1개월 무료',
  'plan_title_lifetime': '평생',
  'best_value': '최고 가치',
  'continue': '계속',
  'try_for_free': '무료로 체험',
  'free': '무료',
  'save_percent': '%{percent} 절약',
  'restore_purchases_success': '프리미엄 구독이 성공적으로 복원되었습니다!',
  'restore_purchases_info': '복원할 활성 프리미엄 구독을 찾을 수 없습니다',
  'restore_purchases_error_premium_expiry_date': '프리미엄 만료 날짜를 가져올 수 없습니다',
  'restore_purchases_error_user_id': '사용자 정보를 찾을 수 없습니다',
  'restore_purchases_error_backend': '백엔드 복원에 실패했습니다',
  'restore_purchases_error_unknown': '복원 중 예상치 못한 오류가 발생했습니다',

  'premium_title': '프리미엄 기능',
  'premium_desc_1': '무제한 피부 분석 수행',
  'premium_desc_2': '최신 AI 모델 사용',
  'premium_desc_3': '이전 분석 결과 보기',
  'premium_restore': '복원',
  'premium_terms': '이용약관',
  'premium_privacy': '개인정보 처리방침',
  'premium_trial_not_available': '무료 체험이 제공되지 않습니다.',
  'premium_continue_without': '프리미엄 없이 계속',
  'premium_no_packages': '구매 옵션을 찾을 수 없습니다.',
  'premium_no_selected_package': '구매할 패키지를 찾을 수 없습니다.',
  'premium_purchase_cancelled': '구매가 취소되었습니다.',
  'premium_purchase_failed': '구매에 실패했습니다. 다시 시도해 주세요.',
  'premium_activated': '프리미엄 구독이 활성화되었습니다!',
  'premium_restore_error': '복원 중 오류가 발생했습니다',

  // 공유
  'share_result_title': '결과 공유',
  'share_result_error': '공유 중 오류가 발생했습니다:',
  'share_result_share_text': 'DermAI - 분석 결과\nDermAI로 피부를 분석하세요!',

  // 프리미엄 기능

  //onboarding
  'onboarding_title_1': 'DermAI에 오신 것을 환영합니다!',
  'onboarding_desc_1': '피부 분석을 위해 사진을 찍거나 이미지를 선택하세요. 피부 문제를 즉시 발견하세요.',
  'onboarding_title_2': '강력한 인공지능',
  'onboarding_desc_2': '가장 진보된 인공지능을 사용하여 최고의 정확도로 피부 분석을 수행합니다.',
  'onboarding_title_3': '결과 발견',
  'onboarding_desc_3': '피부 분석 결과를 보고 피부 문제를 이해하세요.',
  'onboarding_skip': '건너뛰기',
  'onboarding_next': '다음',
  'onboarding_start': '시작',

  //home
  'home_welcome_title': '환영합니다',
  'home_welcome_desc': '피부 분석을 시작하고 이전 결과를 검토하세요.',
  'home_analyze_button_title': '피부 분석을 시작하려면 탭하세요.',
  'home_tip_title': '더 나은 결과를 위해 햇빛이나 밝은 환경에서 사진을 찍으세요.',
  'home_recent_history_title': '최근 활동',
  'home_recent_history_view_more': '더 보기',
  'home_recent_history_no_history': '아직 분석이 수행되지 않았습니다.',
  'home': '홈',
  'history': '기록',

  //camera
  'camera_scan_title': 'DermAI 피부 스캐너',
  'camera_scanning': 'DermAI 분석 중',
  'camera_scanning_desc': '피부 질환이 스캔되고 있습니다...',
  'camera_scan_desc': '피부 질환을 프레임에 맞추세요',

  //history
  'history_no_history': '아직 분석이 수행되지 않았습니다.',

  // 날짜 형식화를 위한 번역 키
  'just_now': '방금',
  'minutes_ago': '{count}분 전',
  'hours_ago': '{count}시간 전',
  'yesterday': '어제',
  'days_ago': '{count}일 전',
  'date_format': 'dd MMM yyyy',

  // 연락처 이메일
  'contact_text': '저희에게 연락하려면 아래 이메일 주소를 사용할 수 있습니다.',
  'contact_mail_subject': 'DermAI - 연락 요청',
  'contact_mail_body_write_here': '여기에 메시지를 작성하세요...',
  'contact_mail_user_id': '사용자 ID',
  'contact_mail_device_type': '기기 유형',
  'contact_mail_app_name': '앱 이름',
  'contact_mail_package_name': '패키지 이름',
  'contact_mail_version': '버전',
  'contact_mail_build_number': '빌드 번호',
  'could_not_open_mail_app': '이메일 앱을 열 수 없습니다',

  // 페이지
  'pages_title': '페이지',
  'pages_empty': '아직 사용할 수 있는 페이지가 없습니다.',
  'page_not_found': '페이지를 찾을 수 없습니다.',
  'loading': '로딩 중...',
  'error': '오류',
  'retry': '다시 시도',

  //result
  'result_title': '결과',
  'result_image_title': '이미지',
  'result_no_result': '결과를 찾을 수 없습니다.',
  'result_disease_name': '질병명',
  'result_contagious': '전염성?',
  'result_severity': '심각도',
  'result_recovery_time': '회복 시간',
  'result_symptoms': '증상',
  'result_body_parts': '영향받은 부위',
  'result_risk_factors': '위험 요인',
  'result_treatment': '의학적 치료',
  'result_prevention': '예방 방법',
  'result_alternative_treatment': '대안 치료',
  'result_description': '설명',
  'result_footer_note': '이 결과는 정보 제공 목적으로만 사용되며 추정 평가입니다. 의사와 상담하세요.',
  'result_image_close': '닫기',
  'result_severity_low': '매우 경미',
  'result_severity_medium': '경미',
  'result_severity_high': '보통',
  'result_severity_very_high': '심각',
  'result_severity_very_very_high': '매우 심각',
  'result_severity_very_very_very_high': '극도로 심각',
  'result_reference': '참고',
  'result_reference_error': '참고 링크를 열 수 없습니다',

  //스캔 대화상자
  'scan_dialog_title': '오류',
  'scan_dialog_title_warning': '경고',
  'scan_dialog_title_error': '오류',
  'scan_dialog_title_info': '정보',
  'scan_dialog_title_success': '성공',
  'scan_dialog_400': '잘못된 데이터가 전송되었습니다.',
  'scan_dialog_403': '프리미엄 구독으로 업그레이드해야 합니다.',
  'scan_dialog_500': 'AI 서비스가 혼잡합니다. 몇 분 후 다시 시도하세요.',
  'scan_dialog_503': '서버 오류가 발생했습니다. 나중에 다시 시도하세요.',
  'scan_dialog_501': '유지보수 모드입니다. 나중에 다시 시도하세요.',
  'scan_dialog_1001': '이미지가 피부와 관련이 없습니다. 또는 피부에 문제가 보이지 않습니다. 새 사진을 찍으세요.',
  'scan_dialog_5000': 'AI 응답을 파싱할 수 없습니다',
  'scan_dialog_429': '너무 많은 요청을 보냈습니다. 나중에 다시 시도하세요.',
  'scan_dialog_error': '오류가 발생했습니다. 나중에 다시 시도하세요.',
  'scan_dialog_ok': '확인',
  'scan_dialog_cancel': '닫기',

  //연락처 대화상자
  'contact_dialog_title': '연락처',
  'contact_dialog_message':
      '저희에게 메시지를 보내기 위해 이메일 앱을 열고 싶으신가요?\n\n이메일 주소: contact@dermai.us',
  'contact_email_copied': '이메일 주소가 복사되었습니다',
  'contact_dialog_cancel': '취소',
  'contact_dialog_send': '이메일 보내기',

  //피부 분석
  'skin_analysis_title': '피부 분석',
  'skin_analysis_age': '나이',
  'skin_analysis_age_info': '나이',
  'skin_analysis_age_info_1': '1세 미만',
  'skin_analysis_button_title': '식별',
  'skin_analysis_button_title_loading': '분석 중...',
  'skin_analysis_scanning': '분석 중...',
  'skin_analysis_scanning_desc': '이미지가 AI에 의해 분석되고 있습니다.\n잠시 기다려 주세요.',
  'skin_analysis_body_parts': '영향받은 부위',
  'skin_analysis_body_parts_selected': '부위 선택됨',
  'skin_analysis_complaints': '세부사항 - 불만사항',
  'skin_analysis_complaints_hint':
      '가려움, 화상, 얼마나 오래, 등 불만사항과 중요한 세부사항을 여기에 작성하세요...',
  'skin_analysis_complaints_char_count': '/500자',
  'skin_analysis_image': '이미지',
  'skin_analysis_body_parts_face': '얼굴',
  'skin_analysis_body_parts_hair': '두피',
  'skin_analysis_body_parts_ear': '귀',
  'skin_analysis_body_parts_neck': '목',
  'skin_analysis_body_parts_hand': '손',
  'skin_analysis_body_parts_leg': '팔',
  'skin_analysis_body_parts_chest': '배',
  'skin_analysis_body_parts_breast': '가슴',
  'skin_analysis_body_parts_back': '등',
  'skin_analysis_body_parts_foot': '발',
  'skin_analysis_body_parts_leg_foot': '다리',
  'skin_analysis_body_parts_sex': '사생활 부위',
  'skin_analysis_token_error': '토큰 확인 중 오류 발생',
  'skin_analysis_token_error_premium': '일일 분석 권한이 소진되었습니다. 프리미엄 구독으로 업그레이드하세요.',
  'skin_analysis_body_parts_error': '최소한 하나의 영향받은 부위를 선택하세요',
  'skin_analysis_complaints_error': '불만사항을 작성하세요',
  'skin_analysis_image_error': '이미지를 찾을 수 없습니다',
  'skin_analysis_error': '분석 중 오류가 발생했습니다. 다시 시도해 주세요.',

  // 법적 경고
  'legal_warning_title': '법적 경고',
  'legal_warning_subtitle': '계속하기 전에 아래 조건을 읽고 동의해 주세요.',
  'legal_warning_description_1':
      '이 앱은 피부 분석을 위해 인공지능 기술을 사용합니다. 분석 결과는 정보 제공 목적으로만 사용되며 의학적 진단을 대체하지 않습니다.',
  'legal_warning_description_2':
      '앱은 분석을 위해 사진을 사용합니다. 이 사진들은 귀하의 기기에만 저장되며 제3자와 공유되지 않습니다.',
  'legal_warning_description_3': '심각한 피부 문제가 있다면 반드시 피부과 의사와 상담하세요.',
  'legal_warning_agreement_title': '이용약관',
  'legal_warning_agreement_1':
      '분석 결과가 정보 제공 목적으로만 사용되며 의학적 진단을 대체하지 않는다는 것에 동의합니다.',
  'legal_warning_agreement_2': '개인정보 처리방침을 읽고 동의했습니다.',
  'legal_warning_agreement_3': '이용약관을 읽고 동의했습니다.',
  'legal_warning_checkbox_text': '위의 조건을 읽고 동의했습니다',
  'legal_warning_confirm_button': '확인',
  'legal_warning_checkbox_text_error': '계속하려면 조건에 동의해 주세요',
  'legal_warning_error': '오류가 발생했습니다. 다시 시도해 주세요',
  'legal_warning_error_no_settings': '링크를 열 수 없습니다',

  //인터넷 없음
  'no_internet_title': '인터넷 연결 없음',
  'no_internet_desc': '저희 앱은 인터넷 연결이 필요합니다. 인터넷 연결을 확인하고 다시 시도해 주세요.',
  'no_internet_retry': '다시 시도',
  'no_internet_connection_established': '연결 설정됨',
  'no_internet_connection_not_established': '연결 없음',
  'no_internet_refresh': '새로 고침',
  'no_internet_settings': '네트워크 설정',
};
