const Map<String, String> zh = {
  'title': 'gemai',

  //settings
  'settings_title': '设置',
  'settings_language': '语言',
  'settings_dark_mode': '深色模式',
  'settings_share': '分享应用',
  'settings_rate': '评价应用',
  'settings_contact': '联系我们',
  'settings_about': '关于',
  'settings_privacy': '隐私政策',
  'settings_terms': '服务条款',
  'settings_faq': '常见问题',
  'settings_version': '版本',
  'settings_restore_purchases': '恢复购买',
  'settings_share_title': '分享应用',
  'settings_rate_title': '评价应用',
  'settings_restore_purchases_success': '购买恢复成功！',
  'settings_restore_purchases_error': '购买恢复失败：',
  'settings_privacy_error': '无法打开隐私政策页面',
  'settings_faq_error': '无法打开常见问题页面',
  'settings_terms_error': '无法打开服务条款页面',
  'settings_about_error': '无法打开关于页面',
  'settings_cancel_subscription_error': '无法打开订阅取消页面',

  //account
  'account_title': '账户',
  'account_anonymous': '匿名用户',
  'account_user_id': '用户ID',
  'account_device_id': '设备ID',
  'account_type': '账户类型',
  'account_type_basic': '基础版',
  'account_type_premium': '高级版',
  'account_remaining_days': '剩余天数',
  'account_remaining_days_info': '天',
  'account_restore_purchases': '恢复购买',
  'account_cancel_subscription': '取消订阅',
  'account_snackbar_copy': '设备ID已复制',

  //premium
  'per_year': '年',
  'per_month': '月',
  'per_week': '周',
  'per_lifetime': '',
  'plan_title_yearly': '年度计划',
  'plan_title_monthly': '月度计划',
  'plan_title_weekly': '周度计划',
  'trial_title_days': '免费{days}天',
  'trial_title_week': '免费1周',
  'trial_title_month': '免费1个月',
  'plan_title_lifetime': '终身',
  'best_value': '最优惠',
  'continue': '继续',
  'try_for_free': '免费试用',
  'free': '免费',
  'save_percent': '节省{percent}%',
  'restore_purchases_success': '高级订阅恢复成功！',
  'restore_purchases_info': '未找到可恢复的活跃高级订阅',
  'restore_purchases_error_premium_expiry_date': '无法获取高级订阅到期日期',
  'restore_purchases_error_user_id': '无法获取用户信息',
  'restore_purchases_error_backend': '后端恢复操作失败',
  'restore_purchases_error_unknown': '恢复过程中发生意外错误',

  'premium_title': '高级功能',
  'premium_desc_1': '无限皮肤分析',
  'premium_desc_2': '使用最新AI模型',
  'premium_desc_3': '查看分析历史',
  'premium_restore': '恢复',
  'premium_terms': '服务条款',
  'premium_privacy': '隐私政策',
  'premium_trial_not_available': '免费试用不可用。',
  'premium_continue_without': '不使用高级功能继续',
  'premium_no_packages': '未找到可购买的高级订阅。',
  'premium_no_selected_package': '未选择要购买的高级订阅。',
  'premium_purchase_cancelled': '购买操作已取消。',
  'premium_purchase_failed': '购买操作失败。请重试。',
  'premium_activated': '高级订阅已激活！',
  'premium_restore_error': '恢复过程中出现错误',

  // 分享
  'share_result_title': '分享结果',
  'share_result_error': '分享时发生错误：',
  'share_result_share_text': 'gemai - 分析结果\n使用gemai分析您的皮肤！',

  //onboarding
  'onboarding_title_1': '欢迎使用gemai！',
  'onboarding_desc_1': '拍摄照片或选择图像来分析您的皮肤。立即发现皮肤问题。',
  'onboarding_title_2': '强大的AI',
  'onboarding_desc_2': '我们使用先进的AI来准确分析皮肤问题。',
  'onboarding_title_3': '发现结果',
  'onboarding_desc_3': '查看您的皮肤分析结果并了解您的皮肤问题。',
  'onboarding_skip': '跳过',
  'onboarding_next': '下一步',
  'onboarding_start': '开始',

  //home
  'home_welcome_title': '欢迎',
  'home_welcome_desc': '开始分析您的皮肤并查看您的历史结果。',
  'home_analyze_button_title': '点击开始皮肤分析。',
  'home_tip_title': '在明亮的环境或白天拍摄照片以获得更好的结果。',
  'home_recent_history_title': '最近的操作',
  'home_recent_history_view_more': '查看更多',
  'home_recent_history_no_history': '还没有分析。',
  'home': '首页',
  'history': '历史',

  //camera
  'camera_scan_title': 'gemai 皮肤扫描器',
  'camera_scanning': 'gemai 分析中',
  'camera_scanning_desc': '正在扫描您的皮肤问题...',
  'camera_scan_desc': '将您的皮肤问题框选起来',

  //history
  'history_no_history': '还没有分析。',

  // 日期格式化翻译键
  'just_now': '刚刚',
  'minutes_ago': '{count} 分钟前',
  'hours_ago': '{count} 小时前',
  'yesterday': '昨天',
  'days_ago': '{count} 天前',
  'date_format': 'yyyy年MM月dd日',

  // Contact mail
  'contact_text': '您可以通过以下电子邮件地址与我们联系。',
  'contact_mail_subject': 'gemai - 联系请求',
  'contact_mail_body_write_here': '请在这里写下您的消息...',
  'contact_mail_user_id': '用户ID',
  'contact_mail_device_type': '设备类型',
  'contact_mail_app_name': '应用名称',
  'contact_mail_package_name': '包名称',
  'contact_mail_version': '版本',
  'contact_mail_build_number': 'Build 编号',
  'could_not_open_mail_app': '邮件应用无法打开',

  // Pages
  'pages_title': '页面',
  'pages_empty': '还没有页面。',
  'page_not_found': '页面不存在。',
  'loading': '加载中...',
  'error': '错误',
  'retry': '重试',

  //result
  'result_title': '结果',
  'result_image_title': '图像',
  'result_no_result': '没有结果。',
  'result_disease_name': '疾病名称',
  'result_contagious': '传染性？',
  'result_severity': '严重程度',
  'result_recovery_time': '恢复时间',
  'result_symptoms': '症状',
  'result_body_parts': '受影响的区域',
  'result_risk_factors': '触发因素',
  'result_treatment': '医疗治疗',
  'result_prevention': '预防方法',
  'result_alternative_treatment': '替代治疗',
  'result_description': '描述',
  'result_footer_note': '这些结果仅用于提供信息，不构成医疗建议。请咨询医生。',
  'result_image_close': '关闭',
  'result_severity_low': '非常轻微',
  'result_severity_medium': '轻微',
  'result_severity_high': '中等',
  'result_severity_very_high': '严重',
  'result_severity_very_very_high': '非常严重',
  'result_severity_very_very_very_high': '极其严重',

  //scan dialogs
  'scan_dialog_title': '错误',
  'scan_dialog_title_warning': '警告',
  'scan_dialog_title_error': '错误',
  'scan_dialog_title_info': '信息',
  'scan_dialog_title_success': '成功',
  'scan_dialog_400': '发送的数据无效。',
  'scan_dialog_403': '需要高级订阅。',
  'scan_dialog_500': 'AI服务繁忙。请几分钟后重试。',
  'scan_dialog_503': '服务器错误。请稍后重试。',
  'scan_dialog_501': '维护中。请稍后重试。',
  'scan_dialog_1001': '图像与皮肤无关。或者您的皮肤上没有可见问题。请重新拍照。',
  'scan_dialog_5000': '无法解析AI响应',
  'scan_dialog_429': '发送了太多请求。请稍后重试。',
  'scan_dialog_error': '发生错误。请稍后重试。',
  'scan_dialog_ok': '确定',
  'scan_dialog_cancel': '关闭',

  //Contact dialog
  'contact_dialog_title': '联系我们',
  'contact_dialog_message': '您想要打开邮件应用向我们发送消息吗？\n\n邮件地址：contact@gemai.us',
  'contact_email_copied': '邮件地址已复制',
  'contact_dialog_cancel': '取消',
  'contact_dialog_send': '发送邮件',

  //skin analysis
  'skin_analysis_title': '皮肤分析',
  'skin_analysis_age': '年龄',
  'skin_analysis_age_info': '年龄',
  'skin_analysis_age_info_1': '1岁以下',
  'skin_analysis_button_title': '分析',
  'skin_analysis_button_title_loading': '分析中...',
  'skin_analysis_scanning': '分析中...',
  'skin_analysis_scanning_desc': '您的图像正在被AI分析。\n请稍候。',
  'skin_analysis_body_parts': '受影响的区域',
  'skin_analysis_body_parts_selected': '区域已选择',
  'skin_analysis_complaints': '详情 - 症状',
  'skin_analysis_complaints_hint': '瘙痒、灼烧感、持续时间等。请在此处写下您的症状和重要详情...',
  'skin_analysis_complaints_char_count': '/500字符',
  'skin_analysis_image': '图像',
  'skin_analysis_body_parts_face': '面部',
  'skin_analysis_body_parts_hair': '头皮',
  'skin_analysis_body_parts_ear': '耳朵',
  'skin_analysis_body_parts_neck': '颈部',
  'skin_analysis_body_parts_hand': '手部',
  'skin_analysis_body_parts_leg': '手臂',
  'skin_analysis_body_parts_chest': '腹部',
  'skin_analysis_body_parts_breast': '胸部',
  'skin_analysis_body_parts_back': '背部',
  'skin_analysis_body_parts_foot': '脚部',
  'skin_analysis_body_parts_leg_foot': '腿部',
  'skin_analysis_body_parts_sex': '生殖器区域',
  'skin_analysis_token_error': '令牌验证过程中发生错误',
  'skin_analysis_token_error_premium': '您的每日分析次数已用完。请升级到高级订阅。',
  'skin_analysis_body_parts_error': '请至少选择一个受影响的区域',
  'skin_analysis_complaints_error': '请写下您的症状',
  'skin_analysis_image_error': '未找到图像',
  'skin_analysis_error': '分析过程中发生错误。请重试。',

  // Legal Warning
  'legal_warning_title': '法律声明',
  'legal_warning_subtitle': '在继续之前，请阅读并接受以下条款。',
  'legal_warning_description_1': '此应用使用人工智能技术进行皮肤分析。分析结果仅供参考，不能替代医疗诊断。',
  'legal_warning_description_2': '应用使用您的照片进行分析。这些照片仅存储在您的设备上，不会与第三方共享。',
  'legal_warning_description_3': '如果您有严重的皮肤问题，请咨询皮肤科医生。',
  'legal_warning_agreement_title': '使用条款',
  'legal_warning_agreement_1': '我接受结果仅供参考，不能替代医疗诊断。',
  'legal_warning_agreement_2': '我已阅读并接受隐私政策。',
  'legal_warning_agreement_3': '我已阅读并接受服务条款。',
  'legal_warning_checkbox_text': '我已阅读并接受上述条款',
  'legal_warning_confirm_button': '确认',
  'legal_warning_checkbox_text_error': '在继续之前请接受条款',
  'legal_warning_error': '发生错误。请重试',
  'legal_warning_error_no_settings': '无法打开链接',

  //no internet
  'no_internet_title': '无网络连接',
  'no_internet_desc': '我们的应用需要网络连接。请检查您的网络连接并重试。',
  'no_internet_retry': '重试',
  'no_internet_connection_established': '连接已建立',
  'no_internet_connection_not_established': '无连接',
  'no_internet_refresh': '刷新',
  'no_internet_settings': '网络设置',
};
